name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      # (Optional — checkout@v4 with lfs:true already pulls LFS objects)
      - name: Ensure LFS files are present
        run: git lfs pull

      - name: Prepare site
        run: |
          mkdir -p _site
          rsync -av --delete \
            --exclude "_site" \
            --exclude ".git" \
            --exclude ".github" \
            --exclude ".gitignore" \
            --exclude "README.md" \
            ./ _site/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
